export const SCAN_UNIVERSE = [
  { ticker: "XAUUSD", name: "Gold Spot / US Dollar", theme: "Gold", price: 2356.4, change: 0.46 },
  { ticker: "NVDA", name: "NVIDIA Corporation", theme: "AI Chip", price: 194.83, change: -1.39 },
  { ticker: "MSFT", name: "Microsoft Corporation", theme: "Cloud AI", price: 493.46, change: 1.02 },
  { ticker: "AAPL", name: "Apple Inc.", theme: "Mega Cap", price: 214.83, change: 0.44 },
  { ticker: "AMZN", name: "Amazon.com, Inc.", theme: "Cloud Commerce", price: 221.3, change: 0.72 },
  { ticker: "META", name: "Meta Platforms, Inc.", theme: "Ads AI", price: 713.5, change: 1.1 },
  { ticker: "GOOGL", name: "Alphabet Inc.", theme: "Search AI", price: 179.2, change: 0.38 },
  { ticker: "TSLA", name: "Tesla, Inc.", theme: "EV Momentum", price: 246.12, change: -1.34 },
  { ticker: "AVGO", name: "Broadcom Inc.", theme: "AI Infra", price: 173.4, change: 1.42 },
  { ticker: "AMD", name: "Advanced Micro Devices", theme: "AI Chip", price: 161.58, change: 1.74 },
  { ticker: "NFLX", name: "Netflix, Inc.", theme: "Streaming", price: 678.2, change: 0.63 },
  { ticker: "COST", name: "Costco Wholesale", theme: "Consumer", price: 884.5, change: 0.22 },
  { ticker: "PLTR", name: "Palantir Technologies", theme: "AI Software", price: 27.8, change: 2.35 },
  { ticker: "ARM", name: "Arm Holdings", theme: "Semiconductor", price: 126.4, change: -0.48 },
  { ticker: "MU", name: "Micron Technology", theme: "Memory", price: 138.7, change: 1.96 },
  { ticker: "QCOM", name: "QUALCOMM Incorporated", theme: "Mobile Chip", price: 196.1, change: 0.84 },
  { ticker: "INTC", name: "Intel Corporation", theme: "Semiconductor", price: 31.2, change: -0.92 },
  { ticker: "ORCL", name: "Oracle Corporation", theme: "Cloud", price: 141.6, change: 0.57 },
  { ticker: "CRM", name: "Salesforce, Inc.", theme: "SaaS", price: 257.9, change: 0.31 },
  { ticker: "NOW", name: "ServiceNow, Inc.", theme: "Enterprise SaaS", price: 749.2, change: 0.66 },
  { ticker: "ADBE", name: "Adobe Inc.", theme: "Creative AI", price: 533.6, change: -0.28 },
  { ticker: "PANW", name: "Palo Alto Networks", theme: "Cybersecurity", price: 321.4, change: 1.17 },
  { ticker: "CRWD", name: "CrowdStrike Holdings", theme: "Cybersecurity", price: 388.5, change: 1.26 },
  { ticker: "SNOW", name: "Snowflake Inc.", theme: "Data Cloud", price: 131.8, change: -0.54 },
  { ticker: "SHOP", name: "Shopify Inc.", theme: "Ecommerce", price: 68.9, change: 1.08 },
  { ticker: "COIN", name: "Coinbase Global", theme: "Crypto Beta", price: 225.1, change: 2.42 },
  { ticker: "MSTR", name: "MicroStrategy Incorporated", theme: "Bitcoin Proxy", price: 1518.7, change: 2.86 },
  { ticker: "JPM", name: "JPMorgan Chase", theme: "Banking", price: 207.5, change: 0.25 },
  { ticker: "BAC", name: "Bank of America", theme: "Banking", price: 39.4, change: -0.18 },
  { ticker: "V", name: "Visa Inc.", theme: "Payments", price: 276.2, change: 0.33 },
  { ticker: "MA", name: "Mastercard Incorporated", theme: "Payments", price: 462.9, change: 0.41 },
  { ticker: "PYPL", name: "PayPal Holdings", theme: "Fintech", price: 63.7, change: 0.79 },
  { ticker: "XOM", name: "Exxon Mobil", theme: "Energy", price: 114.6, change: -0.24 },
  { ticker: "CVX", name: "Chevron Corporation", theme: "Energy", price: 156.8, change: -0.31 },
  { ticker: "OXY", name: "Occidental Petroleum", theme: "Energy", price: 60.1, change: -0.62 },
  { ticker: "LLY", name: "Eli Lilly and Company", theme: "Healthcare", price: 905.4, change: 0.71 },
  { ticker: "UNH", name: "UnitedHealth Group", theme: "Healthcare", price: 492.2, change: -0.43 },
  { ticker: "JNJ", name: "Johnson & Johnson", theme: "Healthcare", price: 148.7, change: 0.14 },
  { ticker: "PFE", name: "Pfizer Inc.", theme: "Healthcare", price: 28.5, change: -0.36 },
  { ticker: "NKE", name: "NIKE, Inc.", theme: "Consumer", price: 94.2, change: 0.22 },
  { ticker: "SBUX", name: "Starbucks Corporation", theme: "Consumer", price: 82.9, change: 0.64 },
  { ticker: "MCD", name: "McDonald's Corporation", theme: "Consumer", price: 289.8, change: 0.19 },
  { ticker: "WMT", name: "Walmart Inc.", theme: "Retail", price: 68.4, change: 0.51 },
  { ticker: "HD", name: "Home Depot", theme: "Retail", price: 356.7, change: 0.27 },
  { ticker: "DIS", name: "The Walt Disney Company", theme: "Media", price: 101.5, change: -0.44 },
  { ticker: "BA", name: "Boeing Company", theme: "Aerospace", price: 184.2, change: -0.83 },
  { ticker: "CAT", name: "Caterpillar Inc.", theme: "Industrial", price: 342.1, change: 0.52 },
  { ticker: "GE", name: "GE Aerospace", theme: "Industrial", price: 159.4, change: 0.68 },
  { ticker: "UBER", name: "Uber Technologies", theme: "Mobility", price: 71.6, change: 1.22 },
  { ticker: "ABNB", name: "Airbnb, Inc.", theme: "Travel", price: 146.3, change: 0.73 },
  { ticker: "SMCI", name: "Super Micro Computer", theme: "AI Server", price: 812.5, change: 2.04 },
];

